### ISSUE TITLE
cant import .rdc to blender

### ISSUE THREAD

**Issue by aombk** [eliemichel/MapsModelsImporter#16]
hello,
i cant import the .rdc file into blender.
tried capturing with RenderDoc 1.1, 1.2 and 1.5
used provided chrome 70something and portable chrome
used Maps Models Importer 0.1.0, 0.1.1, 0.1.2, and 0.1.3
and blender 2.81, 2.81a and 2.82
all possible combinations. or at least many of them
using rtx 2070

during the last attempt though of looking at blender console and i got this:

```
Loading capture from G:\owncloud\compenc\blender\blender scripts\maps models importer\1.rdc...
Couldn't initialise replay: 14
Traceback (most recent call last):
  File "C:\Users\aombk\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 171, in <module>
    main(controller)
  File "C:\Users\aombk\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 83, in main
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'
```

cant wait to be able to use this, looks pretty awesome. thanks.

**Comment by NazzarenoGiannelli** [comment]
I've the same issue, but with a different log outcome:
```
Traceback (most recent call last):
  File "C:\Users\nazza\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\nazza\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps.py", line 179, in importCapture
    prefix = makeTmpDir(pref, filepath)
  File "C:\Users\nazza\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps.py", line 41, in captureToFiles
    python = os.path.join(python_home, "bin", "python.exe" if sys.platform == "win32" else "python3.7m") # warning: hardcoded python version for non-windows might fail with Blender update
  File "E:\Programmi\Blender Foundation\Blender\Blender 2.81\2.81\python\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Programmi\Blender Foundation\Blender\Blender 2.81\2.81\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "E:\Programmi\Blender Foundation\Blender\Blender 2.81\2.81\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

location: <unknown location>:-1
```

No problem with capturing 3d data with an old portable Chromium and RenderDoc 1.1 or 1.2, but importing into Blender doesn't work on 2.81a for me.

I just tested on Blender 2.80 and Maps Models Importer v0.1.2 and it works perfectly, so probably something went wrong during the update to 2.81.

**Comment by aombk** [comment]
just tried with blender 2.80 and Models Importer v0.1.2
still no luck for me. this is the error i am getting now

```
Loading capture from G:\owncloud\compenc\blender\blender scripts\maps models importer\4.rdc...
Couldn't initialise replay: 14
Traceback (most recent call last):
  File "C:\Users\aombk\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 170, in <module>
    with CaptureWrapper(CAPTURE_FILE) as controller:
  File "C:\Users\aombk\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\rdutils.py", line 49, in __enter__
    self.cap.shutdown()
AttributeError: 'renderdoc.CaptureFile' object has no attribute 'shutdown'
```
what am i doing wrong?

**Comment by wangzhongliang** [comment]
> hello,
> i cant import the .rdc file into blender.
> tried capturing with RenderDoc 1.1, 1.2 and 1.5
> used provided chrome 70something and portable chrome
> used Maps Models Importer 0.1.0, 0.1.1, 0.1.2, and 0.1.3
> and blender 2.81, 2.81a and 2.82
> all possible combinations. or at least many of them
> using rtx 2070
> 
> during the last attempt though of looking at blender console and i got this:
> 
> ```
> Loading capture from G:\owncloud\compenc\blender\blender scripts\maps models importer\1.rdc...
> Couldn't initialise replay: 14
> Traceback (most recent call last):
>   File "C:\Users\aombk\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 171, in <module>
>     main(controller)
>   File "C:\Users\aombk\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 83, in main
>     drawcalls = controller.GetDrawcalls()
> AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'
> ```
> 
> cant wait to be able to use this, looks pretty awesome. thanks.

hey aombk,

I have the same issue as you do,

Do you work it out?

**Comment by aombk** [comment]
nope i havent found a solution, i couldnt make it work with previous blender versions etc. im very disappointed this doesnt work for me.
@NazzarenoGiannelli @wangzhongliang what GPUs do you have?
hey @eliemichel could you help with this?

**Comment by mcleanjusten** [comment]
> I've the same issue, but with a different log outcome:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\nazza\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
>     importCapture(context, self.filepath, self.max_blocks, pref)
>   File "C:\Users\nazza\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps.py", line 179, in importCapture
>     prefix = makeTmpDir(pref, filepath)
>   File "C:\Users\nazza\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MapsModelsImporter\google_maps.py", line 41, in captureToFiles
>     python = os.path.join(python_home, "bin", "python.exe" if sys.platform == "win32" else "python3.7m") # warning: hardcoded python version for non-windows might fail with Blender update
>   File "E:\Programmi\Blender Foundation\Blender\Blender 2.81\2.81\python\lib\subprocess.py", line 472, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "E:\Programmi\Blender Foundation\Blender\Blender 2.81\2.81\python\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "E:\Programmi\Blender Foundation\Blender\Blender 2.81\2.81\python\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
> 
> location: <unknown location>:-1
> ```
> 
> No problem with capturing 3d data with an old portable Chromium and RenderDoc 1.1 or 1.2, but importing into Blender doesn't work on 2.81a for me.
> 
> I just tested on Blender 2.80 and Maps Models Importer v0.1.2 and it works perfectly, so probably something went wrong during the update to 2.81.

I was having this issue on 2.80, check if you have multiple versions of blender in 'C:\Program Files\Blender Foundation\Blender' and remove any that do not have python.exe in the python\bin\ folder. For me the issue was blender 2.77 not having the python binary available. I deleted the 2.77 folder and that issue went away.

**Comment by brothermechanic** [comment]
same for me on windows on 2.80 and 2.81a

**Comment by eliemichel** [comment]
@aombk @wangzhongliang @brothermechanic I get a lot of such feedback, but have never been able to reproduce it. The "error 14" is "APIInitFailed" (see [here](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/api/replay/replay_enums.h#L3386)), which can have various causes, from what I can see through a quick search of "APIInitFailed" in RenderDoc's source code.

After you injected RenderDoc into the process, what does it say for you in front of "API"? Is it "OpenGLES" or something else?

@NazzarenoGiannelli It seems to be an unrelated issue. Can you check that there is a file called "python.exe" at location `E:\Programmi\Blender Foundation\Blender\Blender 2.81\2.81\bin`?

**Comment by aombk** [comment]
@eliemichel it says API OpenGLES (active)
so you believe its a renderdoc or injection problem?
not a problem of the blender importer addon?

can someone provide some working .rdc so i can test if i can import ok into blender?
thanks

**Comment by eliemichel** [comment]
OpenGLES is whet is expected. The issue come from the part of the add-on that calls internally the RenderDoc API. I think the capture is good, but cannot be read by the renderdoc.dll built for this add-on. I would have first though about a version missmatch but if you tried all versions (renderdoc 1.1 or 1.2 portable) then it must be that the binary I provide lack support for some things on some hardware.

**Comment by eliemichel** [comment]
@aombk @wangzhongliang @brothermechanic @NazzarenoGiannelli @mcleanjusten The last release [v0.2.0](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc1) should fix all of your issues. Please open new detailed reports if you still run into problems!

**Comment by aombk** [comment]
yes it works now, thank you very much @eliemichel

**Comment by Aliditalia** [comment]
I have downloaded all the last software, Blender 2.90, Renderdoc and your Mapsmodel importer, but when try to import a rdc file I have this error message. Solutions?

Traceback (most recent call last):
  File "C:\Users\PC - FLIGHT\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\PC - FLIGHT\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps.py", line 267, in importCapture
    captureToFiles(context, filepath, prefix, max_blocks)
  File "C:\Users\PC - FLIGHT\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps.py", line 53, in captureToFiles
    out = subprocess.check_output([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)], stderr=subprocess.STDOUT)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 87] Parametro non corretto

location: <unknown location>:-1
