### ISSUE TITLE
Cannot open RDC with latest versions

### ISSUE THREAD

**Issue by hellroy** [eliemichel/MapsModelsImporter#139]
- The .rdc file: https://www.dropbox.com/s/1etgks0l7zp9hra/test3.rdc?dl=0
 - Your GPU name: Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2592 Mhz, 4 Core(s), 8 Logical Processor(s)
 - Version of this add-on: 0.3.5
 - Version of RenderDoc: 1.11
 - Version of Blender: 2.90

Debug info:
google_maps_rd failed and returned:
Loading capture from C:\Users\helsm\Dropbox\3dmodels\Nokia\test3.rdc...
Couldn't initialise replay: 15
This is likely due to an unsupported version of RenderDoc.
Traceback (most recent call last):
  File "C:\Users\helsm\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
    main(controller)
  File "C:\Users\helsm\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
    scraper.run()
  File "C:\Users\helsm\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

Extra info:
 - python = C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin\python.exe
 - python_home = C:\Program Files\Blender Foundation\Blender 2.90\2.90\python

**Comment by hellroy** [comment]
I tried version 1.10 of RenderDoc and it worked. I guess it doesn't like the new version...

**Comment by eliemichel** [comment]
It does not indeed (see [release notes](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1)), could not get the time to update it, and I don't feel in a hurry since it works with RD 1.10!
