### ISSUE TITLE
Couldn't initialise replay: 15

### ISSUE THREAD

**Issue by Fugaxo** [eliemichel/MapsModelsImporter#2]
Hi there

First of all, very well done. Very nice and usefull project. I seem to be running into some problems importing. Here is the output of blender console:

`Read prefs: C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: D:\Users\Pedro\Desktop\Capturar Mapas Google 3d\blender-2.80-513b71c89ad0-win64\blender-2.80.0-git.513b71c89ad0-windows64\2.80\python
Traceback (most recent call last):
  File "D:\Users\Pedro\Desktop\Capturar Mapas Google 3d\blender-2.80-513b71c89ad0-win64\blender-2.80.0-git.513b71c89ad0-windows64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'MapsModelsImporter'
addon_utils.disable: MapsModelsImporter not disabled
Modules Installed (MapsModelsImporter) from 'd:\\Users\\Pedro\\Desktop\\Capturar Mapas Google 3d\\MapsModelsImporter-v0.1.1.zip' into 'C:\\Users\\Pedro\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Writing userprefs: 'C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend' ok
Loading capture from d:\Users\Pedro\Desktop\Captures\nantes.rdc...
Couldn't initialise replay: 15
Traceback (most recent call last):
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 163, in <module>
    with CaptureWrapper(CAPTURE_FILE) as controller:
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\rdutils.py", line 49, in __enter__
    self.cap.shutdown()
AttributeError: 'renderdoc.CaptureFile' object has no attribute 'shutdown'`

Any idea what might be happening? 

Thank you

**Comment by eliemichel** [comment]
Hi @Fugaxo you are not the first to report this issue (but the first on GitHub, thx for opening the thread) in the last two days, and I realize that 2 days ago a new version of RenderDoc has been release.

Could you try capturing the file with the previous version, RenderDoc 1.2: https://github.com/baldurk/renderdoc/releases/tag/v1.2

Thanks
É.

**Comment by DincaAndrei** [comment]
Hi,we talked on youtube about this issue.
I`ve tryed your sample and worked with 1.2 but the result is messy.

![Screenshot (18)](https://user-images.githubusercontent.com/50072561/56862652-d086c100-69b5-11e9-9e2e-492eadd0d2d7.png)

I` tried with my capture test and i get an error

![Screenshot (19)](https://user-images.githubusercontent.com/50072561/56862659-d8defc00-69b5-11e9-8434-d128d5486c71.png)

**Comment by DincaAndrei** [comment]
They updated the v 1.2 aswell

> 

Build | 32-bit Windows | 64-bit Windows | 64-bit Linux
-- | -- | -- | --
RenderDoc v1.2 (Release Notes, 2019-04-26) | Installer (sig) Portable zip (sig) | Installer (sig) Portable zip (sig) | Binary Tarball (sig)

**Comment by Fugaxo** [comment]
Seems to be related with the build of RenderDoc. I tried with portable versions of 1.1 and 1.2 x64 and got some acceptable results

![Capturar](https://user-images.githubusercontent.com/50056185/56871440-ddd39800-6a15-11e9-9cd0-cf9e6a1c0a8f.PNG)
![Capturar2](https://user-images.githubusercontent.com/50056185/56871441-ddd39800-6a15-11e9-9e5e-501b2231dd73.PNG)

**Comment by DincaAndrei** [comment]
Yes i did a test to and works with RenderDoc 1.1

![Screenshot (20)](https://user-images.githubusercontent.com/50072561/56878864-d97f9d00-6a5e-11e9-9179-41c4a453d00d.png)

**Comment by eliemichel** [comment]
Thank both of you for taking the time to test this! I added a note in the README to tell people to download RD 1.1 or 1.2 portable.

@DincaAndrei The result is messy because Google models are messy ;) You can use the zoom out feature of the browser to get a bit more definition in the capture (Google will load higher resolution models, thinking you have a larger screen)

**Comment by luckyday20691** [comment]
Hello guys, i am having an issue like this video in below link. Please tell me know that, what did i do wrong?
Thank you so much!.
https://www.youtube.com/watch?v=X1rswKzCwMM&feature=youtu.be
